AWSTemplateFormatVersion: "2010-09-09"

Description: "This cloudformation template creates a ec2 instance and a security group, security group will be
              attached to the ec2 instance and that allows ssh connection to the ec2 instance"

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-08589eca6dcc9b39c # Amazon Linux AMI Sydney Region, make sure to change the image id based on the Region
      Tags:
        - Key: Name
          Value: Test Instance

        - Key: Author
          Value: !Join [ " ", [ Mohamed, Naushad, Binjima ] ] # have used join Intrinsic Function

      SecurityGroups:
          - !Ref MySecurityGroup

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Public-SSH
      GroupDescription: Allow ssh connection over port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Inboud-Public
